### ISSUE TITLE
Darklaf downgrade

### ISSUE THREAD

**Issue by weisJ** [ByteZ1337/LuytenX#1]
Hi just noticed that you recently downgraded darklaf back to version 2.7.3. Just wondering what the reason for this was. Did you encounter any particular issue?

**Comment by ByteZ1337** [comment]
Pretty sure it was because of this issue: https://github.com/weisJ/darklaf/issues/322. Intellij showed `3.0.0` as the latest version, so I didn't see that it was already fixed.
